### ISSUE TITLE
Theme doesn't work in development with deployed version of Alaveteli

### ISSUE THREAD

**Issue by henare** [Civicsight/accessinfohktheme#6]
The deployed version of our theme (84848b104ff326f7a95ea700b5df753b715d7b27) does not work with our [deployed version of Alaveteli](https://github.com/mysociety/alaveteli/commit/eae7fcd50393e7ac6089e52a40e05dd577147aa7) in development.

When you visit the homepage you get:

```
Sprockets::Rails::Helper::AssetNotPrecompiled (Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( logo-opengraph.png )` to `config/initializers/assets.rb` and restart your server):
  app/views/general/_opengraph_tags.html.erb:29:in `_app_views_general__opengraph_tags_html_erb___3552083688801120953_47162948520180'
  app/views/layouts/default.html.erb:38:in `_app_views_layouts_default_html_erb___3615261468089703054_47162908174060'
  app/controllers/general_controller.rb:30:in `frontpage'
  app/controllers/application_controller.rb:120:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by henare** [comment]
@1000camels this was the underlying problem of the different issues we had with your development instance of Alaveteli.
